return 
{
	["Cfg"] = {
		[11] = {
			["IsEvent"] = true,
			["Level"] = 1,
			["Name"] = "魔族入侵-与米迦勒交谈",
			["NeedTime"] = 1,
			["Options"] = {
				["TaskID"] = 10001,
			},
			["SortID"] = 1,
			["Type"] = "任务完成",
		},
		[12] = {
			["IsEvent"] = true,
			["Level"] = 2,
			["Name"] = "魔族入侵-完成魔族狼骑1战斗（元素教学）",
			["NeedTime"] = 1,
			["Options"] = {
				["TaskID"] = 10002,
			},
			["SortID"] = 2,
			["Type"] = "任务完成",
		},
		[13] = {
			["IsEvent"] = true,
			["Level"] = 3,
			["Name"] = "魔族入侵-与谜之少女交谈",
			["NeedTime"] = 1,
			["Options"] = {
				["TaskID"] = 10003,
			},
			["SortID"] = 3,
			["Type"] = "任务完成",
		},
		[14] = {
			["IsEvent"] = true,
			["Level"] = 4,
			["Name"] = "上阵指引-谜之少女出战",
			["NeedTime"] = 1,
			["Options"] = {
				["TaskID"] = 50001,
			},
			["SortID"] = 4,
			["Type"] = "任务完成",
		},
		[15] = {
			["IsEvent"] = true,
			["Level"] = 4,
			["Name"] = "斩魔-完成魔族狼骑2战斗（元素教学）",
			["NeedTime"] = 2,
			["Options"] = {
				["TaskID"] = 10004,
			},
			["SortID"] = 5,
			["Type"] = "任务完成",
		},
		[16] = {
			["IsEvent"] = true,
			["Level"] = 5,
			["Name"] = "斩魔-完成狼骑统领战斗（自动战斗开启）",
			["NeedTime"] = 2,
			["Options"] = {
				["TaskID"] = 10005,
			},
			["SortID"] = 6,
			["Type"] = "任务完成",
		},
		[17] = {
			["IsEvent"] = true,
			["Level"] = 6,
			["Name"] = "众神殿-神殿激活光子兽",
			["NeedTime"] = 2,
			["Options"] = {
				["TaskID"] = 50037,
			},
			["SortID"] = 7,
			["Type"] = "任务完成",
		},
		[18] = {
			["IsEvent"] = true,
			["Level"] = 6,
			["Name"] = "上阵指引-光子兽出战",
			["NeedTime"] = 2,
			["Options"] = {
				["TaskID"] = 50038,
			},
			["SortID"] = 8,
			["Type"] = "任务完成",
		},
		[19] = {
			["IsEvent"] = true,
			["Level"] = 6,
			["Name"] = "斩魔-与加百列交谈",
			["NeedTime"] = 3,
			["Options"] = {
				["TaskID"] = 10006,
			},
			["SortID"] = 9,
			["Type"] = "任务完成",
		},
		[20] = {
			["IsEvent"] = true,
			["Level"] = 7,
			["Name"] = "斩魔-完成艾斯摩尔战斗（展示加百列、米迦勒技能）",
			["NeedTime"] = 4,
			["Options"] = {
				["TaskID"] = 10007,
			},
			["SortID"] = 10,
			["Type"] = "任务完成",
		},
		[21] = {
			["IsEvent"] = false,
			["Level"] = 8,
			["Name"] = "出现命名界面",
			["NeedTime"] = 4,
			["SortID"] = 11,
			["Type"] = "出现命名界面",
		},
		[22] = {
			["IsEvent"] = false,
			["Level"] = 8,
			["Name"] = "命名成功",
			["NeedTime"] = 4,
			["SortID"] = 12,
			["Type"] = "命名成功",
		},
		[23] = {
			["IsEvent"] = true,
			["Level"] = 8,
			["Name"] = "家园重建-与瑞克交谈",
			["NeedTime"] = 4,
			["Options"] = {
				["TaskID"] = 10008,
			},
			["SortID"] = 13,
			["Type"] = "任务完成",
		},
		[24] = {
			["IsEvent"] = true,
			["Level"] = 9,
			["Name"] = "家园重建-与雷诺交谈",
			["NeedTime"] = 4,
			["Options"] = {
				["TaskID"] = 10009,
			},
			["SortID"] = 14,
			["Type"] = "任务完成",
		},
		[25] = {
			["IsEvent"] = true,
			["Level"] = 9,
			["Name"] = "家园重建-收集3堆木材（蘑灵幻境）",
			["NeedTime"] = 5,
			["Options"] = {
				["TaskID"] = 10010,
			},
			["SortID"] = 15,
			["Type"] = "任务完成",
		},
		[26] = {
			["IsEvent"] = true,
			["Level"] = 9,
			["Name"] = "家园重建-与雷诺交谈",
			["NeedTime"] = 5,
			["Options"] = {
				["TaskID"] = 10011,
			},
			["SortID"] = 16,
			["Type"] = "任务完成",
		},
		[27] = {
			["IsEvent"] = true,
			["Level"] = 10,
			["Name"] = "足迹-与丽莎交谈",
			["NeedTime"] = 5,
			["Options"] = {
				["TaskID"] = 10012,
			},
			["SortID"] = 17,
			["Type"] = "任务完成",
		},
		[28] = {
			["IsEvent"] = true,
			["Level"] = 10,
			["Name"] = "足迹-完成副本战斗（蘑灵幻境）",
			["NeedTime"] = 6,
			["Options"] = {
				["TaskID"] = 10013,
			},
			["SortID"] = 18,
			["Type"] = "任务完成",
		},
		[29] = {
			["IsEvent"] = true,
			["Level"] = 11,
			["Name"] = "足迹-与丽莎交谈",
			["NeedTime"] = 6,
			["Options"] = {
				["TaskID"] = 10014,
			},
			["SortID"] = 19,
			["Type"] = "任务完成",
		},
		[30] = {
			["IsEvent"] = true,
			["Level"] = 12,
			["Name"] = "森林探查-与雷诺交谈",
			["NeedTime"] = 6,
			["Options"] = {
				["TaskID"] = 10015,
			},
			["SortID"] = 20,
			["Type"] = "任务完成",
		},
		[31] = {
			["IsEvent"] = true,
			["Level"] = 12,
			["Name"] = "森林探查-完成副本战斗（月光森林1）",
			["NeedTime"] = 7,
			["Options"] = {
				["TaskID"] = 10016,
			},
			["SortID"] = 21,
			["Type"] = "任务完成",
		},
		[32] = {
			["IsEvent"] = true,
			["Level"] = 13,
			["Name"] = "森林探查-与雷诺交谈",
			["NeedTime"] = 7,
			["Options"] = {
				["TaskID"] = 10017,
			},
			["SortID"] = 22,
			["Type"] = "任务完成",
		},
		[33] = {
			["IsEvent"] = true,
			["Level"] = 14,
			["Name"] = "森林探查-与瑞克交谈",
			["NeedTime"] = 7,
			["Options"] = {
				["TaskID"] = 10018,
			},
			["SortID"] = 23,
			["Type"] = "任务完成",
		},
		[34] = {
			["IsEvent"] = true,
			["Level"] = 14,
			["Name"] = "失踪的人-完成副本战斗（月光森林2）",
			["NeedTime"] = 9,
			["Options"] = {
				["TaskID"] = 10019,
			},
			["SortID"] = 24,
			["Type"] = "任务完成",
		},
		[35] = {
			["IsEvent"] = true,
			["Level"] = 15,
			["Name"] = "失踪的人-与铁匠交谈",
			["NeedTime"] = 9,
			["Options"] = {
				["TaskID"] = 10020,
			},
			["SortID"] = 25,
			["Type"] = "任务完成",
		},
		[36] = {
			["IsEvent"] = true,
			["Level"] = 16,
			["Name"] = "完成第一次强化-装备强化3次",
			["NeedTime"] = 9,
			["Options"] = {
				["TaskID"] = 50004,
			},
			["SortID"] = 26,
			["Type"] = "任务完成",
		},
		[37] = {
			["IsEvent"] = true,
			["Level"] = 16,
			["Name"] = "失踪的人-与铁匠交谈",
			["NeedTime"] = 10,
			["Options"] = {
				["TaskID"] = 10021,
			},
			["SortID"] = 27,
			["Type"] = "任务完成",
		},
		[38] = {
			["IsEvent"] = true,
			["Level"] = 16,
			["Name"] = "夺回矿石-完成副本战斗（月光森林3）",
			["NeedTime"] = 11,
			["Options"] = {
				["TaskID"] = 19001,
			},
			["SortID"] = 28,
			["Type"] = "任务完成",
		},
		[39] = {
			["IsEvent"] = true,
			["Level"] = 16,
			["Name"] = "夺回矿石-与耶林萨交谈",
			["NeedTime"] = 11,
			["Options"] = {
				["TaskID"] = 19002,
			},
			["SortID"] = 29,
			["Type"] = "任务完成",
		},
		[40] = {
			["IsEvent"] = true,
			["Level"] = 17,
			["Name"] = "完成第二次强化-装备强化3次",
			["NeedTime"] = 11,
			["Options"] = {
				["TaskID"] = 50028,
			},
			["SortID"] = 30,
			["Type"] = "任务完成",
		},
		[41] = {
			["IsEvent"] = true,
			["Level"] = 17,
			["Name"] = "失踪的人-与雷诺交谈",
			["NeedTime"] = 11,
			["Options"] = {
				["TaskID"] = 10022,
			},
			["SortID"] = 31,
			["Type"] = "任务完成",
		},
		[42] = {
			["IsEvent"] = true,
			["Level"] = 17,
			["Name"] = "进入神殿-完成副本战斗（远古神殿1）",
			["NeedTime"] = 12,
			["Options"] = {
				["TaskID"] = 10023,
			},
			["SortID"] = 32,
			["Type"] = "任务完成",
		},
		[43] = {
			["IsEvent"] = true,
			["Level"] = 17,
			["Name"] = "进入神殿-与雷诺交谈",
			["NeedTime"] = 12,
			["Options"] = {
				["TaskID"] = 10024,
			},
			["SortID"] = 33,
			["Type"] = "任务完成",
		},
		[44] = {
			["IsEvent"] = true,
			["Level"] = 18,
			["Name"] = "进入神殿-与露娜交谈",
			["NeedTime"] = 12,
			["Options"] = {
				["TaskID"] = 10025,
			},
			["SortID"] = 34,
			["Type"] = "任务完成",
		},
		[45] = {
			["IsEvent"] = true,
			["Level"] = 18,
			["Name"] = "神殿真相-完成水龙战斗（远古神殿2，展示帕修斯）",
			["NeedTime"] = 14,
			["Options"] = {
				["TaskID"] = 10027,
			},
			["SortID"] = 35,
			["Type"] = "任务完成",
		},
		[46] = {
			["IsEvent"] = true,
			["Level"] = 19,
			["Name"] = "告别-与瑞克交谈",
			["NeedTime"] = 14,
			["Options"] = {
				["TaskID"] = 10028,
			},
			["SortID"] = 36,
			["Type"] = "任务完成",
		},
		[47] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "告别-与雷诺交谈",
			["NeedTime"] = 14,
			["Options"] = {
				["TaskID"] = 10029,
			},
			["SortID"] = 37,
			["Type"] = "任务完成",
		},
		[48] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "告别-与耶林萨交谈",
			["NeedTime"] = 14,
			["Options"] = {
				["TaskID"] = 10030,
			},
			["SortID"] = 38,
			["Type"] = "任务完成",
		},
		[49] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "完成第三次强化-装备强化4次",
			["NeedTime"] = 15,
			["Options"] = {
				["TaskID"] = 50029,
			},
			["SortID"] = 39,
			["Type"] = "任务完成",
		},
		[50] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "曙光之城-与拉菲交谈",
			["NeedTime"] = 15,
			["Options"] = {
				["TaskID"] = 10031,
			},
			["SortID"] = 40,
			["Type"] = "任务完成",
		},
		[51] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "曙光之城-与亚瑟交谈",
			["NeedTime"] = 15,
			["Options"] = {
				["TaskID"] = 10032,
			},
			["SortID"] = 41,
			["Type"] = "任务完成",
		},
		[52] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "古怪-与阿芙洛狄特交谈",
			["NeedTime"] = 15,
			["Options"] = {
				["TaskID"] = 10036,
			},
			["SortID"] = 42,
			["Type"] = "任务完成",
		},
		[53] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "魔族阴谋-完成副本战斗（水晶汐地1）",
			["NeedTime"] = 17,
			["Options"] = {
				["TaskID"] = 10038,
			},
			["SortID"] = 43,
			["Type"] = "任务完成",
		},
		[54] = {
			["IsEvent"] = true,
			["Level"] = 20,
			["Name"] = "魔族阴谋-与亚瑟交谈",
			["NeedTime"] = 17,
			["Options"] = {
				["TaskID"] = 10039,
			},
			["SortID"] = 44,
			["Type"] = "任务完成",
		},
		[55] = {
			["IsEvent"] = true,
			["Level"] = 21,
			["Name"] = "坐骑开启-坐骑幻化",
			["NeedTime"] = 18,
			["Options"] = {
				["TaskID"] = 50014,
			},
			["SortID"] = 45,
			["Type"] = "任务完成",
		},
		[56] = {
			["IsEvent"] = true,
			["Level"] = 21,
			["Name"] = "指引坐骑乘骑",
			["NeedTime"] = 18,
			["Options"] = {
				["TaskID"] = 51011,
			},
			["SortID"] = 46,
			["Type"] = "任务完成",
		},
		[57] = {
			["IsEvent"] = true,
			["Level"] = 21,
			["Name"] = "魔族阴谋-与塔塔交谈",
			["NeedTime"] = 18,
			["Options"] = {
				["TaskID"] = 10040,
			},
			["SortID"] = 47,
			["Type"] = "任务完成",
		},
		[58] = {
			["IsEvent"] = true,
			["Level"] = 21,
			["Name"] = "神秘少年-完成副本战斗（水晶汐地2） ",
			["NeedTime"] = 19,
			["Options"] = {
				["TaskID"] = 19003,
			},
			["SortID"] = 48,
			["Type"] = "任务完成",
		},
		[59] = {
			["IsEvent"] = true,
			["Level"] = 21,
			["Name"] = "魔族阴谋-与亚瑟交谈",
			["NeedTime"] = 19,
			["Options"] = {
				["TaskID"] = 19004,
			},
			["SortID"] = 49,
			["Type"] = "任务完成",
		},
		[60] = {
			["IsEvent"] = true,
			["Level"] = 22,
			["Name"] = "魔族阴谋-完成副本战斗（水晶汐地3）",
			["NeedTime"] = 20,
			["Options"] = {
				["TaskID"] = 10041,
			},
			["SortID"] = 50,
			["Type"] = "任务完成",
		},
		[61] = {
			["IsEvent"] = true,
			["Level"] = 22,
			["Name"] = "魔族阴谋-与塔塔交谈",
			["NeedTime"] = 20,
			["Options"] = {
				["TaskID"] = 10042,
			},
			["SortID"] = 51,
			["Type"] = "任务完成",
		},
		[62] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "新的矿源-与耶林萨交谈",
			["NeedTime"] = 20,
			["Options"] = {
				["TaskID"] = 10043,
			},
			["SortID"] = 52,
			["Type"] = "任务完成",
		},
		[63] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "完成第四次强化-武器强化到10级（进入剧情副本扫荡5次）",
			["NeedTime"] = 21,
			["Options"] = {
				["TaskID"] = 50017,
			},
			["SortID"] = 53,
			["Type"] = "任务完成",
		},
		[64] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "完成首次冒险之路挑战（水晶汐地1） ",
			["NeedTime"] = 23,
			["Options"] = {
				["TaskID"] = 50018,
			},
			["SortID"] = 54,
			["Type"] = "任务完成",
		},
		[65] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "指引装备进阶-武器进阶",
			["NeedTime"] = 23,
			["Options"] = {
				["TaskID"] = 51008,
			},
			["SortID"] = 55,
			["Type"] = "任务完成",
		},
		[66] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "魔族动向-与战克交谈",
			["NeedTime"] = 23,
			["Options"] = {
				["TaskID"] = 10044,
			},
			["SortID"] = 56,
			["Type"] = "任务完成",
		},
		[67] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "魔族动向-与亚瑟交谈",
			["NeedTime"] = 24,
			["Options"] = {
				["TaskID"] = 10045,
			},
			["SortID"] = 57,
			["Type"] = "任务完成",
		},
		[68] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "魔族动向-完成副本战斗（流金峡谷）",
			["NeedTime"] = 25,
			["Options"] = {
				["TaskID"] = 10046,
			},
			["SortID"] = 58,
			["Type"] = "任务完成",
		},
		[69] = {
			["IsEvent"] = true,
			["Level"] = 23,
			["Name"] = "魔族手段-与亚瑟交谈",
			["NeedTime"] = 25,
			["Options"] = {
				["TaskID"] = 10047,
			},
			["SortID"] = 59,
			["Type"] = "任务完成",
		},
	},
	["Name2ID"] = {
		["上阵指引-光子兽出战"] = 18,
		["上阵指引-谜之少女出战"] = 14,
		["众神殿-神殿激活光子兽"] = 17,
		["出现命名界面"] = 21,
		["古怪-与阿芙洛狄特交谈"] = 52,
		["告别-与瑞克交谈"] = 46,
		["告别-与耶林萨交谈"] = 48,
		["告别-与雷诺交谈"] = 47,
		["命名成功"] = 22,
		["坐骑开启-坐骑幻化"] = 55,
		["失踪的人-与铁匠交谈"] = 37,
		["失踪的人-与雷诺交谈"] = 41,
		["失踪的人-完成副本战斗（月光森林2）"] = 34,
		["夺回矿石-与耶林萨交谈"] = 39,
		["夺回矿石-完成副本战斗（月光森林3）"] = 38,
		["完成第一次强化-装备强化3次"] = 36,
		["完成第三次强化-装备强化4次"] = 49,
		["完成第二次强化-装备强化3次"] = 40,
		["完成第四次强化-武器强化到10级（进入剧情副本扫荡5次）"] = 63,
		["完成首次冒险之路挑战（水晶汐地1） "] = 64,
		["家园重建-与瑞克交谈"] = 23,
		["家园重建-与雷诺交谈"] = 26,
		["家园重建-收集3堆木材（蘑灵幻境）"] = 25,
		["指引坐骑乘骑"] = 56,
		["指引装备进阶-武器进阶"] = 65,
		["斩魔-与加百列交谈"] = 19,
		["斩魔-完成狼骑统领战斗（自动战斗开启）"] = 16,
		["斩魔-完成艾斯摩尔战斗（展示加百列、米迦勒技能）"] = 20,
		["斩魔-完成魔族狼骑2战斗（元素教学）"] = 15,
		["新的矿源-与耶林萨交谈"] = 62,
		["曙光之城-与亚瑟交谈"] = 51,
		["曙光之城-与拉菲交谈"] = 50,
		["森林探查-与瑞克交谈"] = 33,
		["森林探查-与雷诺交谈"] = 32,
		["森林探查-完成副本战斗（月光森林1）"] = 31,
		["神殿真相-完成水龙战斗（远古神殿2，展示帕修斯）"] = 45,
		["神秘少年-完成副本战斗（水晶汐地2） "] = 58,
		["足迹-与丽莎交谈"] = 29,
		["足迹-完成副本战斗（蘑灵幻境）"] = 28,
		["进入神殿-与雷诺交谈"] = 43,
		["进入神殿-与露娜交谈"] = 44,
		["进入神殿-完成副本战斗（远古神殿1）"] = 42,
		["魔族入侵-与米迦勒交谈"] = 11,
		["魔族入侵-与谜之少女交谈"] = 13,
		["魔族入侵-完成魔族狼骑1战斗（元素教学）"] = 12,
		["魔族动向-与亚瑟交谈"] = 67,
		["魔族动向-与战克交谈"] = 66,
		["魔族动向-完成副本战斗（流金峡谷）"] = 68,
		["魔族手段-与亚瑟交谈"] = 69,
		["魔族阴谋-与亚瑟交谈"] = 59,
		["魔族阴谋-与塔塔交谈"] = 61,
		["魔族阴谋-完成副本战斗（水晶汐地1）"] = 53,
		["魔族阴谋-完成副本战斗（水晶汐地3）"] = 60,
	},
}