return 
{
	["tblAddPlayerLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家账号',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '注册时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Sex` int(11) DEFAULT '1' COMMENT '性别',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家注册日志表']],
	["tblGoldLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家ID',
  `Changes` int(11) DEFAULT '0' COMMENT '钻石变化数',
  `Reason` varchar(64) NOT NULL DEFAULT '' COMMENT '变更原因',
  `Remain` int(11) DEFAULT '0' COMMENT '当前钻石数',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='钻石日志表']],
	["tblInstanceLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `StageId` varchar(32) NOT NULL DEFAULT '' COMMENT '副本ID',
  `StageType` varchar(32) NOT NULL DEFAULT '' COMMENT '副本名称',
  `Times` int(11) NOT NULL DEFAULT '0' COMMENT '次数',
  `NotPassEvent` varchar(32) NOT NULL DEFAULT '' COMMENT '未通过回合',
  `CardList` varchar(32) NOT NULL DEFAULT '' COMMENT '上阵阵型',
  `Bonus` varchar(256) NOT NULL DEFAULT '' COMMENT '奖励',
  `IsFinish` tinyint(4) NOT NULL DEFAULT '0' COMMENT '星级评定',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`Uid`),
  KEY `index3` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='副本日志表']],
	["tblItemLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `OperationType` tinyint(4) NOT NULL DEFAULT '1' COMMENT ' 操作类型:1:获得，2:删除',
  `Type` varchar(20) NOT NULL DEFAULT '' COMMENT '变化类型',
  `Reason` varchar(64) NOT NULL DEFAULT '' COMMENT '变更原因',
  `Memo` varchar(32) NOT NULL DEFAULT '' COMMENT '备注',
  `ItemName` varchar(32) NOT NULL DEFAULT '' COMMENT '物品名称',
  `ItemType` int(11) NOT NULL DEFAULT '0' COMMENT '物品ID',
  `Amount` int(11) NOT NULL DEFAULT '0' COMMENT '物品数量',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  `ItemUid` bigint(20) NOT NULL DEFAULT '-1' COMMENT '物品Uid',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='物品日志表']],
	["tblLevelUpLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家ID',
  `Type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '升级类型，1:LevelUp,2:addplayer',
  `OrgLevel` int(11) NOT NULL DEFAULT '1' COMMENT '原等级',
  `NewLevel` int(11) NOT NULL DEFAULT '1' COMMENT '现等级',
  `Exp` int(11) NOT NULL DEFAULT '0' COMMENT '经验值',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '升级时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家升级日志表']],
	["tblLoginLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家账号',
  `Ip` varchar(32) NOT NULL DEFAULT '' COMMENT '登录IP',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Name` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家角色名',
  `Level` int(11) NOT NULL DEFAULT '0' COMMENT '玩家等级',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家登录日志表']],
	["tblLogoutLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家账号',
  `OnTime` int(11) NOT NULL DEFAULT '0' COMMENT '在线时长（秒）',
  `Level` int(11) NOT NULL DEFAULT '0' COMMENT '等级',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '退出时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `VipLevel` tinyint(4) DEFAULT '0' COMMENT 'VIP等级',
  `IsVip` tinyint(4) DEFAULT '0' COMMENT 'VIP是否激活状态',
  `Gold` int(11) DEFAULT '0' COMMENT '钻石数(非绑钻)',
  `TotalGold` int(11) DEFAULT '0' COMMENT '总钻石数(绑钻+非绑钻)',
  `Money` int(11) DEFAULT '0' COMMENT '金币数',
  `Ip` varchar(32) NOT NULL DEFAULT '' COMMENT 'IP地址',
  `Name` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家退出日志表']],
	["tblMessageLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `SenderName` varchar(32) NOT NULL DEFAULT '' COMMENT '发信人',
  `Title` varchar(128) NOT NULL DEFAULT '' COMMENT '标题',
  `Content` varchar(256) NOT NULL DEFAULT '' COMMENT '内容',
  `Bonus` varchar(128) NOT NULL DEFAULT '' COMMENT '奖励内容',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  `SenderUid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `TargetUid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`Uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='邮件日志表']],
	["tblMoneyLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Changes` int(11) DEFAULT '0' COMMENT '金钱变化数',
  `Reason` varchar(64) NOT NULL DEFAULT '' COMMENT '变更原因',
  `Remain` int(11) DEFAULT '0' COMMENT '当前金钱数',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Name` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='金钱日志表']],
	["tblRenameLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `OldName` varchar(32) NOT NULL DEFAULT '' COMMENT '活动名称',
  `NewName` varchar(32) NOT NULL DEFAULT '' COMMENT '活动名称',
  `NameChangedTime` int(11) NOT NULL DEFAULT '0' COMMENT '改名次数',
  `Time` datetime DEFAULT NULL COMMENT '时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='重命名日志表']],
}