return 
{
	["tblActLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `ActName` varchar(32) NOT NULL DEFAULT '' COMMENT '活动名称',
  `Status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态:1=参与，2=完成',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='活动参与记录表']],
	["tblAddPlayerLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Sex` int(11) DEFAULT '1' COMMENT '性别',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家注册日志表']],
	["tblChatLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `ChannelID` tinyint(4) NOT NULL DEFAULT '1' COMMENT '频道ID',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  `Msg` varchar(512) NOT NULL DEFAULT '' COMMENT '聊天内容',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='聊天记录表']],
	["tblClientLoadLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Vfd` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家进程ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Step` int(11) NOT NULL DEFAULT '1' COMMENT '执行步骤',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `IP` varchar(32) NOT NULL DEFAULT '' COMMENT 'IP地址',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户端模块加载日志表']],
	["tblGoldLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Changes` int(11) DEFAULT '0' COMMENT '钻石变化数',
  `Reason` varchar(64) NOT NULL DEFAULT '' COMMENT '变更原因',
  `Remain` int(11) DEFAULT '0' COMMENT '当前钻石数',
  `GoldType` tinyint(4) DEFAULT '1' COMMENT '钻石类型,1:gold,2:creditgold',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='钻石日志表']],
	["tblInstanceLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `InstanceType` int(11) NOT NULL DEFAULT '0' COMMENT '副本类型ID',
  `InstanceID` varchar(32) NOT NULL DEFAULT '' COMMENT '副本ID',
  `InstanceName` varchar(64) NOT NULL DEFAULT '' COMMENT '副本名称',
  `OperationType` tinyint(4) NOT NULL DEFAULT '1' COMMENT '操作类型,1:挑战,2:扫荡',
  `Num` int(11) NOT NULL DEFAULT '0' COMMENT '次数',
  `Result` tinyint(4) NOT NULL DEFAULT '-1' COMMENT '结果,1:成功,0:失败,-1:无',
  `Reward` varchar(128) NOT NULL DEFAULT '' COMMENT '奖励',
  `Star` tinyint(4) NOT NULL DEFAULT '0' COMMENT '星级评定',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`Uid`),
  KEY `index3` (`Name`),
  KEY `index4` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='副本日志表']],
	["tblItemLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `OperationType` tinyint(4) NOT NULL DEFAULT '1' COMMENT ' 操作类型:1:获得，2:删除',
  `Type` varchar(20) NOT NULL DEFAULT '' COMMENT '变化类型',
  `Reason` varchar(64) NOT NULL DEFAULT '' COMMENT '变更原因',
  `Memo` varchar(32) NOT NULL DEFAULT '' COMMENT '备注',
  `ItemName` varchar(64) NOT NULL DEFAULT '' COMMENT '物品名称',
  `ItemType` int(11) NOT NULL DEFAULT '0' COMMENT '物品ID',
  `ShowType` int(11) NOT NULL DEFAULT '0' COMMENT '类型ID',
  `Amount` int(11) NOT NULL DEFAULT '0' COMMENT '物品数量',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  `Position` tinyint(4) NOT NULL DEFAULT '1' COMMENT '物品位置,0:立即使用,1:背包，2:临时背包,3:装备',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='物品日志表']],
	["tblLevelUpLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '升级类型，1:LevelUp,2:addplayer',
  `OrgLevel` int(11) NOT NULL DEFAULT '1' COMMENT '原等级',
  `NewLevel` int(11) NOT NULL DEFAULT '1' COMMENT '现等级',
  `Exp` int(11) NOT NULL DEFAULT '0' COMMENT '经验值',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '升级时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家升级日志表']],
	["tblLoginLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Ip` varchar(32) NOT NULL DEFAULT '' COMMENT '登录IP',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `Name` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家角色名',
  `Lv` int(11) NOT NULL DEFAULT '0' COMMENT '玩家等级',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家登录日志表']],
	["tblLogoutLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '平台账号',
  `OnTime` int(11) NOT NULL DEFAULT '0' COMMENT '在线时长（秒）',
  `Lv` int(11) NOT NULL DEFAULT '0' COMMENT '等级',
  `SceneUid` int(11) NOT NULL DEFAULT '0' COMMENT '场景uid',
  `X` int(11) NOT NULL DEFAULT '0' COMMENT 'X坐标',
  `Y` int(11) NOT NULL DEFAULT '0' COMMENT 'Y坐标',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '退出时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `VipLevel` tinyint(4) DEFAULT '0' COMMENT 'VIP等级',
  `IsVip` tinyint(4) DEFAULT '0' COMMENT 'VIP是否激活状态',
  `Fighting` int(11) DEFAULT '0' COMMENT '战斗力',
  `Name` varchar(64) DEFAULT '' COMMENT '角色名',
  `Gold` int(11) DEFAULT '0' COMMENT '钻石数(非绑钻)',
  `TotalGold` int(11) DEFAULT '0' COMMENT '总钻石数(绑钻+非绑钻)',
  `Money` int(11) DEFAULT '0' COMMENT '金币数',
  `Ip` varchar(32) NOT NULL DEFAULT '' COMMENT 'IP地址',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家退出日志表']],
	["tblMessageLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `SenderName` varchar(32) NOT NULL DEFAULT '' COMMENT '发信人',
  `MessageType` tinyint(4) NOT NULL DEFAULT '1' COMMENT '邮件类型,1:奖励,2:提示',
  `Title` varchar(128) NOT NULL DEFAULT '' COMMENT '标题',
  `Content` varchar(256) NOT NULL DEFAULT '' COMMENT '内容',
  `Bonus` varchar(128) NOT NULL DEFAULT '' COMMENT '奖励内容',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`Uid`),
  KEY `index3` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='邮件日志表']],
	["tblMoneyLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Changes` int(11) DEFAULT '0' COMMENT '金钱变化数',
  `Reason` varchar(64) NOT NULL DEFAULT '' COMMENT '变更原因',
  `Remain` int(11) DEFAULT '0' COMMENT '当前金钱数',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
  `Flag` varchar(8) NOT NULL DEFAULT 'true' COMMENT '标志位',
  `GoldType` tinyint(4) DEFAULT '3' COMMENT '金币类型,3:money',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `Type` varchar(16) NOT NULL DEFAULT 'Money' COMMENT '货币类型',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='金钱日志表']],
	["tblPayLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `OrderID` varchar(32) NOT NULL DEFAULT '' COMMENT '订单ID',
  `Args` varchar(256) NOT NULL DEFAULT '' COMMENT '回调参数',
  `Result` varchar(32) NOT NULL DEFAULT '' COMMENT '返回结果',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`OrderID`),
  KEY `index2` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='充值日志表']],
	["tblRenameLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '新角色名',
  `OrgName` varchar(32) NOT NULL DEFAULT '' COMMENT '原角色名',
  `Time` datetime DEFAULT NULL COMMENT '时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='重命名日志表']],
	["tblShopBuyLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `ShopID` int(11) NOT NULL DEFAULT '0' COMMENT '商店ID',
  `ItemID` int(11) NOT NULL DEFAULT '0' COMMENT '购买物品ID',
  `ItemType` varchar(16) NOT NULL DEFAULT '' COMMENT '物品类型',
  `ItemName` varchar(32) NOT NULL DEFAULT '' COMMENT '商品名称',
  `Currency` varchar(16) NOT NULL DEFAULT '' COMMENT '货币类型',
  `Amount` int(11) NOT NULL DEFAULT '0' COMMENT '购买数量',
  `Price` int(11) NOT NULL DEFAULT '0' COMMENT '消费金额',
  `Memo` varchar(48) NOT NULL DEFAULT '' COMMENT '消费备注',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商城购买记录表']],
	["tblTaskLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Task` int(11) NOT NULL DEFAULT '0' COMMENT '任务ID',
  `Type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '类型（1:接受任务；2:完成任务）',
  `TaskType` tinyint(4) NOT NULL DEFAULT '1' COMMENT '任务类型（1:主线任务；2:其他任务）',
  `Time` datetime DEFAULT NULL COMMENT '接受/完成时间',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务日志表']],
  ["tblExpLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `OrgExp` int NOT NULL DEFAULT '0' COMMENT '原经验',
  `ExpChange` int NOT NULL DEFAULT '0' COMMENT '获得经验',
  `CurExp` int NOT NULL DEFAULT '0' COMMENT '现经验',
  `OrgLevel` int NOT NULL DEFAULT '1' COMMENT '原等级',
  `CurLevel` int NOT NULL DEFAULT '1' COMMENT '现等级',
  `Reason` varchar(32) NOT NULL DEFAULT '' COMMENT '获得经验原因',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='玩家经验日志表']],
  ["tblGodDoorLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `DoorType` int NOT NULL DEFAULT '1' COMMENT '抽奖类型',
  `SubType` int NOT NULL DEFAULT '0' COMMENT '子类型',
  `Reward` varchar(128) NOT NULL DEFAULT '' COMMENT '奖励列表',
  `Consume` varchar(128) NOT NULL DEFAULT '' COMMENT '消耗列表',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='众神之门抽奖日志表']],
  ["tblPetLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `OperationType` tinyint NOT NULL DEFAULT '1' COMMENT '操作类型',
  `PetID` int NOT NULL DEFAULT '0' COMMENT '宠物ID',
  `NeedResource` varchar(128) NOT NULL DEFAULT '' COMMENT '消耗资源',
  `Result` varchar(64) NOT NULL DEFAULT '' COMMENT '操作结果',
  `PetUid` bigint(20) NOT NULL DEFAULT '0' COMMENT '魔神Uid',
  `Level` int NOT NULL DEFAULT '0' COMMENT '魔神等级',
  `StarLevel` int NOT NULL DEFAULT '0' COMMENT '魔神星级',
  `Fighting` int NOT NULL DEFAULT '0' COMMENT '魔神战斗力',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='宠物日志表']],
  ["tblPetDayStatics"] = [[(
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `PetUid` bigint(20) NOT NULL DEFAULT '0' COMMENT '魔神Uid',
  `Date` date NOT NULL DEFAULT '0000-00-00' COMMENT '统计日期',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `PetID` int NOT NULL DEFAULT '0' COMMENT '宠物ID',
  `Level` int NOT NULL DEFAULT '0' COMMENT '魔神等级',
  `StarLevel` int NOT NULL DEFAULT '0' COMMENT '魔神星级',
  `Fighting` int NOT NULL DEFAULT '0' COMMENT '魔神战斗力',
  PRIMARY KEY (`HostID`,`PetUid`,`Date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='魔神日统计表']],
  ["tblPetEquipLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `Position` varchar(8) NOT NULL DEFAULT '' COMMENT '位置',
  `Consume` varchar(128) NOT NULL DEFAULT '' COMMENT '消耗列表',
  `OperationType` tinyint(4) NOT NULL DEFAULT '1' COMMENT '类型（1:进阶；2:强化,3:附魔）',
  `NewItemName`varchar(32) NOT NULL DEFAULT '' COMMENT '操作后物品名称',
  `Time` datetime DEFAULT NULL COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='魔神装备日志表']],
  ["tblPetBrandLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `Grid` tinyint(4) NOT NULL DEFAULT '1' COMMENT '位置',
  `ConsumeNum` int(11) NOT NULL DEFAULT '0' COMMENT '消耗数量',
  `Level` int(11) NOT NULL DEFAULT '0' COMMENT '辉印等级',
  `Time` datetime DEFAULT NULL COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='魔神辉印日志表']],
  ["tblTeamInstLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `StageId` int(11) NOT NULL DEFAULT '0' COMMENT '副本等级',
  `SubStageId` tinyint(4) NOT NULL DEFAULT '1' COMMENT '副本难度',
  `Rewards` varchar(128) NOT NULL DEFAULT '' COMMENT '奖励列表',
  `Type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '类型（1:进入副本,2:通关,3:基本奖励,4:附加奖励）',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='诸神黄昏日志表']],
  ["tblMountLevelLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家角色ID',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `MountID` int(11) NOT NULL DEFAULT '0' COMMENT '坐骑ID',
  `TransID` int(11) NOT NULL DEFAULT '0' COMMENT '幻化ID',
  `OrgEvoLevel` tinyint(4) NOT NULL DEFAULT '0' COMMENT '原有幻化等阶',
  `NewEvoLevel` tinyint(4) NOT NULL DEFAULT '0' COMMENT '新幻化等阶',
  `OrgExp` int(11) NOT NULL DEFAULT '0' COMMENT '原有培养值',
  `NewExp` int(11) NOT NULL DEFAULT '0' COMMENT '现培养值',
  `Consumes` varchar(128) NOT NULL DEFAULT '' COMMENT '消耗列表',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='坐骑升阶日志表']],
  ["tblPetSoulLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(32) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `OperationType` tinyint(4) NOT NULL DEFAULT '1' COMMENT '操作类型,1替换2镶嵌3卸下4合成',
  `Grid` int(11) NOT NULL DEFAULT '1' COMMENT '魔神栏ID',
  `Consume` varchar(128) NOT NULL DEFAULT '' COMMENT '消耗列表',
  `ItemType` int(11) NOT NULL DEFAULT '0' COMMENT '物品ID',
  `Amount` int(11) NOT NULL DEFAULT '0' COMMENT '物品数量',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='宝石日志表']],
  ["tblEndlessBattlelLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Name` varchar(32) NOT NULL DEFAULT '' COMMENT '角色名',
  `ExitType` tinyint(4) NOT NULL DEFAULT '1' COMMENT '退出类型,1手动退出2死亡退出',
  `CurStage` int(11) NOT NULL DEFAULT '0' COMMENT '通关层数',
  `Rewards` varchar(128) NOT NULL DEFAULT '' COMMENT '奖励列表',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='方舟之战日志表']],
  ["tblLottoLog"] = [[(
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HostID` int(11) NOT NULL DEFAULT '0' COMMENT '服ID',
  `Uid` bigint(20) NOT NULL DEFAULT '0' COMMENT '玩家账号ID',
  `Urs` varchar(64) NOT NULL DEFAULT '' COMMENT '平台账号',
  `Name` varchar(64) NOT NULL DEFAULT '' COMMENT '玩家角色名',
  `Rate` decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT '兑换倍数',
  `PayGold` int(11) NOT NULL DEFAULT '0' COMMENT '充值钻石',
  `ExchangeGold` int(11) NOT NULL DEFAULT '0' COMMENT '兑换钻石',
  `LottoTime` timestamp NOT NULL DEFAULT '1971-01-01 01:00:01' COMMENT '抽奖时间',
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  PRIMARY KEY (`ID`),
  KEY `index1` (`Time`),
  KEY `index2` (`HostID`,`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='乐透转盘兑换表']],
}