return 
{
	["Attribute"] = {
		["BaseAtr"] = {
			["BlessValue"] = {
				["CnName"] = "祝福值",
				["Const"] = 0,
			},
			["Exp"] = {
				["CnName"] = "经验值",
				["Const"] = 0,
			},
			["Id"] = {
				["CnName"] = "坐骑ID",
			},
			["Name"] = {
				["CnName"] = "坐骑名称",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["TransAtk"] = {
				["CnName"] = "幻化攻击",
				["Const"] = 0,
			},
			["TransDef"] = {
				["CnName"] = "幻化防御",
				["Const"] = 0,
			},
			["TransId"] = {
				["CnName"] = "幻化ID",
			},
			["TransMaxHp"] = {
				["CnName"] = "幻化生命",
				["Const"] = 0,
			},
			["TransSkillId"] = {
				["CnName"] = "幻化技能ID",
				["Const"] = 0,
			},
			["TransSpeed"] = {
				["CnName"] = "幻化速度",
				["Const"] = 0,
			},
		},
		["BuildAtr"] = {
			["Atk"] = {
				["CnName"] = "攻击",
				["Formula"] = "return function (self) return self:GetAtkBase() + self:GetTransAtk() end",
			},
			["AtkBase"] = {
				["CnName"] = "基础攻击",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["BaseRunSpeed"] = {
				["CnName"] = "基础移动速度",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["BlessLimit"] = {
				["CnName"] = "祝福值上限",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["Def"] = {
				["CnName"] = "防御",
				["Formula"] = "return function (self) return self:GetDefBase() + self:GetTransDef() end",
			},
			["DefBase"] = {
				["CnName"] = "基础防御",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["EvoLevel"] = {
				["CnName"] = "等阶",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["FaceIcon"] = {
				["CnName"] = "头像",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["Fighting"] = {
				["CnName"] = " 战斗力",
				["Formula"] = "return function (self) return math.floor(self:GetMaxHp()*1+self:GetAtk()*10+self:GetDef()*10+self:GetSpeed()*10) end",
			},
			["GuardSkill"] = {
				["CnName"] = "守护技能ID",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["IsFly"] = {
				["CnName"] = "是否飞行",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["Level"] = {
				["CnName"] = "星级",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["LevelLimit"] = {
				["CnName"] = "等级上限",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["MaxExp"] = {
				["CnName"] = "经验值上限",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["MaxHp"] = {
				["CnName"] = "生命",
				["Formula"] = "return function (self) return self:GetMaxHpBase() + self:GetTransMaxHp() end",
			},
			["MaxHpBase"] = {
				["CnName"] = "基础生命",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["NeedItemAmount"] = {
				["CnName"] = "进阶消耗道具数量",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["NeedItems"] = {
				["CnName"] = "进阶消耗道具ID",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["NeedMoney"] = {
				["CnName"] = "进阶消耗金币量",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["Quality"] = {
				["CnName"] = "品质",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["RunSpeed"] = {
				["CnName"] = "移动速度",
				["Formula"] = "return function (self) if self:GetTransRunSpeed() and self:GetTransRunSpeed()>0 then return self:GetTransRunSpeed() else return self:GetBaseRunSpeed() end end",
			},
			["ShapeId"] = {
				["CnName"] = "造型",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["SkillDesc"] = {
				["CnName"] = "技能描述文字",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["SkillIcon"] = {
				["CnName"] = "技能图标资源ID",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["SkillName"] = {
				["CnName"] = "技能名称",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["SkillType"] = {
				["CnName"] = "技能类型",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["Speed"] = {
				["CnName"] = "速度",
				["Formula"] = "return function (self) return self:GetSpeedBase() + self:GetTransSpeed() end",
			},
			["SpeedBase"] = {
				["CnName"] = "基础速度",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["SuccessRate"] = {
				["CnName"] = "成功率",
				["Formula"] = "return function (self) if self:GetBlessValue()<self:GetBlessLimit()*0.6 then return 0 elseif self:GetBlessValue()<self:GetBlessLimit()*0.8 then return ((self:GetBlessValue()-self:GetBlessLimit()*0.6+1)/self:GetBlessLimit())^math.max(1,self:GetEvoLevel()/6) else return 1 end end",
			},
			["TalentSkillList"] = {
				["CnName"] = "天赋技",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["TargetId"] = {
				["CnName"] = "进阶目标坐骑ID",
				["KeyName"] = "Id",
				["SheetName"] = "坐骑数据表",
			},
			["TransAtkBase"] = {
				["CnName"] = "幻化基础攻击",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["TransDefBase"] = {
				["CnName"] = "幻化基础防御",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["TransMaxHpBase"] = {
				["CnName"] = "幻化基础生命",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["TransRunSpeed"] = {
				["CnName"] = "幻化移动速度",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
			["TransSpeedBase"] = {
				["CnName"] = "幻化基础速度",
				["KeyName"] = "TransSkillId",
				["SheetName"] = "幻化技能表",
			},
		},
	},
	["ConstInfo"] = {
		["坐骑数据表"] = {
			{
				["AtkBase"] = 30,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 30,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 300,
				["MaxHpBase"] = 280,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					1,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 6,
				["TargetId"] = 2,
			},
			{
				["AtkBase"] = 84,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 84,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 500,
				["MaxHpBase"] = 840,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					1,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 17,
				["TargetId"] = 3,
			},
			{
				["AtkBase"] = 167,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 167,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 900,
				["MaxHpBase"] = 1670,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					1,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 33,
				["TargetId"] = 4,
			},
			{
				["AtkBase"] = 251,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 251,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 1700,
				["MaxHpBase"] = 2510,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					1,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 50,
				["TargetId"] = 5,
			},
			{
				["AtkBase"] = 335,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 335,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 1400,
				["MaxHpBase"] = 3350,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					2,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 67,
				["TargetId"] = 6,
			},
			{
				["AtkBase"] = 418,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 418,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 1300,
				["MaxHpBase"] = 4180,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					3,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 84,
				["TargetId"] = 7,
			},
			{
				["AtkBase"] = 502,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 502,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 1400,
				["MaxHpBase"] = 5020,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					4,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 100,
				["TargetId"] = 8,
			},
			{
				["AtkBase"] = 586,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 586,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 1300,
				["MaxHpBase"] = 5860,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					6,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 117,
				["TargetId"] = 9,
			},
			{
				["AtkBase"] = 669,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 669,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 1400,
				["MaxHpBase"] = 6690,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					7,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 134,
				["TargetId"] = 10,
			},
			{
				["AtkBase"] = 753,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 753,
				["EvoLevel"] = 1,
				["FaceIcon"] = 16001,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 1600,
				["MaxHpBase"] = 7530,
				["Name"] = "飞鸿",
				["NeedItemAmount"] = {
					8,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 1,
				["ShapeId"] = 140015,
				["SpeedBase"] = 151,
				["TargetId"] = 11,
			},
			{
				["AtkBase"] = 837,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 837,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 1600,
				["MaxHpBase"] = 8370,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					10,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 167,
				["TargetId"] = 12,
			},
			{
				["AtkBase"] = 920,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 920,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 1600,
				["MaxHpBase"] = 9200,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					12,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 184,
				["TargetId"] = 13,
			},
			{
				["AtkBase"] = 1004,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1004,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 1700,
				["MaxHpBase"] = 10040,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					14,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 201,
				["TargetId"] = 14,
			},
			{
				["AtkBase"] = 1087,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1087,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 1800,
				["MaxHpBase"] = 10870,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					16,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 217,
				["TargetId"] = 15,
			},
			{
				["AtkBase"] = 1171,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1171,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 2100,
				["MaxHpBase"] = 11710,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					17,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 234,
				["TargetId"] = 16,
			},
			{
				["AtkBase"] = 1255,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1255,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 2100,
				["MaxHpBase"] = 12550,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					20,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 251,
				["TargetId"] = 17,
			},
			{
				["AtkBase"] = 1338,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1338,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 2300,
				["MaxHpBase"] = 13380,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					22,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 268,
				["TargetId"] = 18,
			},
			{
				["AtkBase"] = 1422,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1422,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 2400,
				["MaxHpBase"] = 14220,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					24,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 284,
				["TargetId"] = 19,
			},
			{
				["AtkBase"] = 1506,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1506,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 2700,
				["MaxHpBase"] = 15060,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					26,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 301,
				["TargetId"] = 20,
			},
			{
				["AtkBase"] = 1589,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1589,
				["EvoLevel"] = 2,
				["FaceIcon"] = 16002,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 2400,
				["MaxHpBase"] = 15890,
				["Name"] = "冰狼",
				["NeedItemAmount"] = {
					28,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 2,
				["ShapeId"] = 140003,
				["SpeedBase"] = 318,
				["TargetId"] = 21,
			},
			{
				["AtkBase"] = 1673,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1673,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 2500,
				["MaxHpBase"] = 16730,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					31,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 335,
				["TargetId"] = 22,
			},
			{
				["AtkBase"] = 1849,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 1849,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 2700,
				["MaxHpBase"] = 18490,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					33,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 370,
				["TargetId"] = 23,
			},
			{
				["AtkBase"] = 2034,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 2034,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 2700,
				["MaxHpBase"] = 20340,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					36,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 407,
				["TargetId"] = 24,
			},
			{
				["AtkBase"] = 2228,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 2228,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 2900,
				["MaxHpBase"] = 22280,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					38,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 446,
				["TargetId"] = 25,
			},
			{
				["AtkBase"] = 2431,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 2431,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 3000,
				["MaxHpBase"] = 24310,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					41,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 486,
				["TargetId"] = 26,
			},
			{
				["AtkBase"] = 2643,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 2643,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 3200,
				["MaxHpBase"] = 26430,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					43,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 529,
				["TargetId"] = 27,
			},
			{
				["AtkBase"] = 2864,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 2864,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 3300,
				["MaxHpBase"] = 28640,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					46,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 573,
				["TargetId"] = 28,
			},
			{
				["AtkBase"] = 3095,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 3095,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 3400,
				["MaxHpBase"] = 30950,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					49,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 619,
				["TargetId"] = 29,
			},
			{
				["AtkBase"] = 3334,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 3334,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 3500,
				["MaxHpBase"] = 33340,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					52,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 667,
				["TargetId"] = 30,
			},
			{
				["AtkBase"] = 3583,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 3583,
				["EvoLevel"] = 3,
				["FaceIcon"] = 16003,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 3400,
				["MaxHpBase"] = 35830,
				["Name"] = "白虎",
				["NeedItemAmount"] = {
					54,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 3,
				["ShapeId"] = 140004,
				["SpeedBase"] = 717,
				["TargetId"] = 31,
			},
			{
				["AtkBase"] = 3841,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 3841,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 3500,
				["MaxHpBase"] = 38410,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					57,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 768,
				["TargetId"] = 32,
			},
			{
				["AtkBase"] = 4108,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 4108,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 3700,
				["MaxHpBase"] = 41080,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					60,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 822,
				["TargetId"] = 33,
			},
			{
				["AtkBase"] = 4384,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 4384,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 3800,
				["MaxHpBase"] = 43840,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					63,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 877,
				["TargetId"] = 34,
			},
			{
				["AtkBase"] = 4669,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 4669,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 3900,
				["MaxHpBase"] = 46690,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					66,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 934,
				["TargetId"] = 35,
			},
			{
				["AtkBase"] = 4964,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 4964,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 4100,
				["MaxHpBase"] = 49640,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					69,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 993,
				["TargetId"] = 36,
			},
			{
				["AtkBase"] = 5268,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 5268,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 4200,
				["MaxHpBase"] = 52680,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					72,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 1054,
				["TargetId"] = 37,
			},
			{
				["AtkBase"] = 5581,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 5581,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 4300,
				["MaxHpBase"] = 55810,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					75,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 1116,
				["TargetId"] = 38,
			},
			{
				["AtkBase"] = 5904,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 5904,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 4500,
				["MaxHpBase"] = 59040,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					78,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 1181,
				["TargetId"] = 39,
			},
			{
				["AtkBase"] = 6235,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 6235,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 4600,
				["MaxHpBase"] = 62350,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					81,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 1247,
				["TargetId"] = 40,
			},
			{
				["AtkBase"] = 6576,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 6576,
				["EvoLevel"] = 4,
				["FaceIcon"] = 16004,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 4500,
				["MaxHpBase"] = 65760,
				["Name"] = "战熊",
				["NeedItemAmount"] = {
					85,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 4,
				["ShapeId"] = 140008,
				["SpeedBase"] = 1315,
				["TargetId"] = 41,
			},
			{
				["AtkBase"] = 6927,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 6927,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 4700,
				["MaxHpBase"] = 69270,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					88,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1385,
				["TargetId"] = 42,
			},
			{
				["AtkBase"] = 7286,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 7286,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 4800,
				["MaxHpBase"] = 72860,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					91,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1457,
				["TargetId"] = 43,
			},
			{
				["AtkBase"] = 7655,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 7655,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 5000,
				["MaxHpBase"] = 76550,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					94,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1531,
				["TargetId"] = 44,
			},
			{
				["AtkBase"] = 8034,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 8034,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 5100,
				["MaxHpBase"] = 80340,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					98,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1607,
				["TargetId"] = 45,
			},
			{
				["AtkBase"] = 8421,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 8421,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 5200,
				["MaxHpBase"] = 84210,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					101,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1684,
				["TargetId"] = 46,
			},
			{
				["AtkBase"] = 8818,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 8818,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 5400,
				["MaxHpBase"] = 88180,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					104,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1764,
				["TargetId"] = 47,
			},
			{
				["AtkBase"] = 9225,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 9225,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 5500,
				["MaxHpBase"] = 92250,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					108,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1845,
				["TargetId"] = 48,
			},
			{
				["AtkBase"] = 9641,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 9641,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 5600,
				["MaxHpBase"] = 96410,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					111,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 1928,
				["TargetId"] = 49,
			},
			{
				["AtkBase"] = 10066,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 10066,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 5800,
				["MaxHpBase"] = 100660,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					114,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 2013,
				["TargetId"] = 50,
			},
			{
				["AtkBase"] = 10500,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 10500,
				["EvoLevel"] = 5,
				["FaceIcon"] = 16005,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 5900,
				["MaxHpBase"] = 105000,
				["Name"] = "星骓",
				["NeedItemAmount"] = {
					118,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140002,
				["SpeedBase"] = 2100,
				["TargetId"] = 51,
			},
			{
				["AtkBase"] = 10944,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 10944,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 6100,
				["MaxHpBase"] = 109440,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					121,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2189,
				["TargetId"] = 52,
			},
			{
				["AtkBase"] = 11398,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 11398,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 6200,
				["MaxHpBase"] = 113980,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					125,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2280,
				["TargetId"] = 53,
			},
			{
				["AtkBase"] = 11861,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 11861,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 6400,
				["MaxHpBase"] = 118610,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					128,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2372,
				["TargetId"] = 54,
			},
			{
				["AtkBase"] = 12333,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 12333,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 6500,
				["MaxHpBase"] = 123330,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					132,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2467,
				["TargetId"] = 55,
			},
			{
				["AtkBase"] = 12815,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 12815,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 6600,
				["MaxHpBase"] = 128150,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					136,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2563,
				["TargetId"] = 56,
			},
			{
				["AtkBase"] = 13306,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 13306,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 6800,
				["MaxHpBase"] = 133060,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					139,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2661,
				["TargetId"] = 57,
			},
			{
				["AtkBase"] = 13807,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 13807,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 6900,
				["MaxHpBase"] = 138070,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					143,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2761,
				["TargetId"] = 58,
			},
			{
				["AtkBase"] = 14317,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 14317,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 7000,
				["MaxHpBase"] = 143170,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					146,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2863,
				["TargetId"] = 59,
			},
			{
				["AtkBase"] = 14836,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 14836,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 7200,
				["MaxHpBase"] = 148360,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					150,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 2967,
				["TargetId"] = 60,
			},
			{
				["AtkBase"] = 15366,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 15366,
				["EvoLevel"] = 6,
				["FaceIcon"] = 16006,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 7300,
				["MaxHpBase"] = 153660,
				["Name"] = "地狱爵士",
				["NeedItemAmount"] = {
					154,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 5,
				["ShapeId"] = 140001,
				["SpeedBase"] = 3073,
				["TargetId"] = 61,
			},
			{
				["AtkBase"] = 15904,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 15904,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 7400,
				["MaxHpBase"] = 159040,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					158,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3181,
				["TargetId"] = 62,
			},
			{
				["AtkBase"] = 16452,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 16452,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 7600,
				["MaxHpBase"] = 164520,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					161,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3291,
				["TargetId"] = 63,
			},
			{
				["AtkBase"] = 17010,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 17010,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 7700,
				["MaxHpBase"] = 170100,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					165,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3402,
				["TargetId"] = 64,
			},
			{
				["AtkBase"] = 17577,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 17577,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 7800,
				["MaxHpBase"] = 175770,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					169,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3515,
				["TargetId"] = 65,
			},
			{
				["AtkBase"] = 18154,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 18154,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 7900,
				["MaxHpBase"] = 181540,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					173,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3631,
				["TargetId"] = 66,
			},
			{
				["AtkBase"] = 18740,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 18740,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 8100,
				["MaxHpBase"] = 187400,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					176,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3748,
				["TargetId"] = 67,
			},
			{
				["AtkBase"] = 19336,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 19336,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 8300,
				["MaxHpBase"] = 193360,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					180,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3867,
				["TargetId"] = 68,
			},
			{
				["AtkBase"] = 19941,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 19941,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 8400,
				["MaxHpBase"] = 199410,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					184,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 3988,
				["TargetId"] = 69,
			},
			{
				["AtkBase"] = 20556,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 20556,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 8500,
				["MaxHpBase"] = 205560,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					188,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 4111,
				["TargetId"] = 70,
			},
			{
				["AtkBase"] = 21181,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 21181,
				["EvoLevel"] = 7,
				["FaceIcon"] = 16007,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 8700,
				["MaxHpBase"] = 211810,
				["Name"] = "独角兽王",
				["NeedItemAmount"] = {
					192,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140011,
				["SpeedBase"] = 4236,
				["TargetId"] = 71,
			},
			{
				["AtkBase"] = 21815,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 21815,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 8800,
				["MaxHpBase"] = 218150,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					196,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 4363,
				["TargetId"] = 72,
			},
			{
				["AtkBase"] = 22459,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 22459,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 8900,
				["MaxHpBase"] = 224590,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					200,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 4492,
				["TargetId"] = 73,
			},
			{
				["AtkBase"] = 23112,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 23112,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 9100,
				["MaxHpBase"] = 231120,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					204,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 4622,
				["TargetId"] = 74,
			},
			{
				["AtkBase"] = 23775,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 23775,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 9200,
				["MaxHpBase"] = 237750,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					208,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 4755,
				["TargetId"] = 75,
			},
			{
				["AtkBase"] = 24447,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 24447,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 9300,
				["MaxHpBase"] = 244470,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					212,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 4889,
				["TargetId"] = 76,
			},
			{
				["AtkBase"] = 25129,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 25129,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 9500,
				["MaxHpBase"] = 251290,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					216,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 5026,
				["TargetId"] = 77,
			},
			{
				["AtkBase"] = 25821,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 25821,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 9600,
				["MaxHpBase"] = 258210,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					220,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 5164,
				["TargetId"] = 78,
			},
			{
				["AtkBase"] = 26522,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 26522,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 9700,
				["MaxHpBase"] = 265220,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					224,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 5304,
				["TargetId"] = 79,
			},
			{
				["AtkBase"] = 27233,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 27233,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 9900,
				["MaxHpBase"] = 272330,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					228,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 5447,
				["TargetId"] = 80,
			},
			{
				["AtkBase"] = 27954,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 27954,
				["EvoLevel"] = 8,
				["FaceIcon"] = 16012,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 10000,
				["MaxHpBase"] = 279540,
				["Name"] = "傲世霸王",
				["NeedItemAmount"] = {
					232,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140017,
				["SpeedBase"] = 5591,
				["TargetId"] = 81,
			},
			{
				["AtkBase"] = 28684,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 28684,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 10200,
				["MaxHpBase"] = 286840,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					236,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 5737,
				["TargetId"] = 82,
			},
			{
				["AtkBase"] = 29424,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 29424,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 10300,
				["MaxHpBase"] = 294240,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					240,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 5885,
				["TargetId"] = 83,
			},
			{
				["AtkBase"] = 30173,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 30173,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 10500,
				["MaxHpBase"] = 301730,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					244,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6035,
				["TargetId"] = 84,
			},
			{
				["AtkBase"] = 30932,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 30932,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 10500,
				["MaxHpBase"] = 309320,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					249,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6187,
				["TargetId"] = 85,
			},
			{
				["AtkBase"] = 31701,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 31701,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 10700,
				["MaxHpBase"] = 317010,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					253,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6340,
				["TargetId"] = 86,
			},
			{
				["AtkBase"] = 32480,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 32480,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 10800,
				["MaxHpBase"] = 324800,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					257,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6496,
				["TargetId"] = 87,
			},
			{
				["AtkBase"] = 33268,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 33268,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 11000,
				["MaxHpBase"] = 332680,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					261,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6654,
				["TargetId"] = 88,
			},
			{
				["AtkBase"] = 34066,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 34066,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 11100,
				["MaxHpBase"] = 340660,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					265,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6813,
				["TargetId"] = 89,
			},
			{
				["AtkBase"] = 34873,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 34873,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 11200,
				["MaxHpBase"] = 348730,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					270,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 6975,
				["TargetId"] = 90,
			},
			{
				["AtkBase"] = 35690,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 35690,
				["EvoLevel"] = 9,
				["FaceIcon"] = 16009,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 356900,
				["Name"] = "圣徒",
				["NeedItemAmount"] = {
					274,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140012,
				["SpeedBase"] = 7138,
				["TargetId"] = 91,
			},
			{
				["AtkBase"] = 36517,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 36517,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 1,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 365170,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					281,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 7304,
				["TargetId"] = 92,
			},
			{
				["AtkBase"] = 37354,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 37354,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 2,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 373540,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					288,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 7471,
				["TargetId"] = 93,
			},
			{
				["AtkBase"] = 38200,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 38200,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 3,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 382000,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					295,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 7640,
				["TargetId"] = 94,
			},
			{
				["AtkBase"] = 39056,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 39056,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 4,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 390560,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					303,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 7811,
				["TargetId"] = 95,
			},
			{
				["AtkBase"] = 39922,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 39922,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 5,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 399220,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					310,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 7984,
				["TargetId"] = 96,
			},
			{
				["AtkBase"] = 40798,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 40798,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 6,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 407980,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					318,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 8160,
				["TargetId"] = 97,
			},
			{
				["AtkBase"] = 41683,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 41683,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 7,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 416830,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					326,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 8337,
				["TargetId"] = 98,
			},
			{
				["AtkBase"] = 42578,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 42578,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 8,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 425780,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					333,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 8516,
				["TargetId"] = 99,
			},
			{
				["AtkBase"] = 43483,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 43483,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 9,
				["MaxExp"] = 11400,
				["MaxHpBase"] = 434830,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					341,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 8697,
				["TargetId"] = 100,
			},
			{
				["AtkBase"] = 44397,
				["BaseRunSpeed"] = 100,
				["BlessLimit"] = 999999,
				["DefBase"] = 44397,
				["EvoLevel"] = 10,
				["FaceIcon"] = 16010,
				["IsFly"] = false,
				["Level"] = 10,
				["MaxExp"] = 99999999,
				["MaxHpBase"] = 443970,
				["Name"] = "光辉",
				["NeedItemAmount"] = {
					341,
				},
				["NeedItems"] = {
					71032,
				},
				["NeedMoney"] = 0,
				["Quality"] = 6,
				["ShapeId"] = 140013,
				["SpeedBase"] = 8879,
			},
		},
		["幻化技能表"] = {
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16001,
				["SkillName"] = "幻化技·飞鸿",
				["SkillType"] = 2,
				["TransAtkBase"] = 25,
				["TransDefBase"] = 25,
				["TransMaxHpBase"] = 250,
				["TransRunSpeed"] = 130,
				["TransSpeedBase"] = 5,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16005,
				["SkillName"] = "幻化技·战马",
				["SkillType"] = 2,
				["TransAtkBase"] = 50,
				["TransDefBase"] = 50,
				["TransMaxHpBase"] = 500,
				["TransRunSpeed"] = 135,
				["TransSpeedBase"] = 10,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16002,
				["SkillName"] = "幻化技·雪原狼",
				["SkillType"] = 2,
				["TransAtkBase"] = 75,
				["TransDefBase"] = 75,
				["TransMaxHpBase"] = 750,
				["TransRunSpeed"] = 140,
				["TransSpeedBase"] = 15,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16004,
				["SkillName"] = "幻化技·装甲熊",
				["SkillType"] = 2,
				["TransAtkBase"] = 100,
				["TransDefBase"] = 100,
				["TransMaxHpBase"] = 1000,
				["TransRunSpeed"] = 145,
				["TransSpeedBase"] = 20,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16006,
				["SkillName"] = "幻化技·梦魇战骑",
				["SkillType"] = 2,
				["TransAtkBase"] = 125,
				["TransDefBase"] = 125,
				["TransMaxHpBase"] = 1250,
				["TransRunSpeed"] = 150,
				["TransSpeedBase"] = 25,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16014,
				["SkillName"] = "幻化技·玩具火箭",
				["SkillType"] = 2,
				["TransAtkBase"] = 50,
				["TransDefBase"] = 50,
				["TransMaxHpBase"] = 500,
				["TransRunSpeed"] = 145,
				["TransSpeedBase"] = 10,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16011,
				["SkillName"] = "幻化技·熊猫銮",
				["SkillType"] = 2,
				["TransAtkBase"] = 100,
				["TransDefBase"] = 100,
				["TransMaxHpBase"] = 1000,
				["TransRunSpeed"] = 145,
				["TransSpeedBase"] = 20,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16014,
				["SkillName"] = "幻化技·核弹头",
				["SkillType"] = 2,
				["TransAtkBase"] = 75,
				["TransDefBase"] = 75,
				["TransMaxHpBase"] = 750,
				["TransRunSpeed"] = 140,
				["TransSpeedBase"] = 15,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16003,
				["SkillName"] = "幻化技·水晶圣兽",
				["SkillType"] = 2,
				["TransAtkBase"] = 125,
				["TransDefBase"] = 125,
				["TransMaxHpBase"] = 1250,
				["TransRunSpeed"] = 150,
				["TransSpeedBase"] = 25,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16017,
				["SkillName"] = "幻化技·皇族狮鹫",
				["SkillType"] = 2,
				["TransAtkBase"] = 125,
				["TransDefBase"] = 125,
				["TransMaxHpBase"] = 1250,
				["TransRunSpeed"] = 130,
				["TransSpeedBase"] = 25,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16007,
				["SkillName"] = "幻化技·彤云天马",
				["SkillType"] = 2,
				["TransAtkBase"] = 150,
				["TransDefBase"] = 150,
				["TransMaxHpBase"] = 1500,
				["TransRunSpeed"] = 140,
				["TransSpeedBase"] = 30,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16015,
				["SkillName"] = "幻化技·秘银战车",
				["SkillType"] = 2,
				["TransAtkBase"] = 150,
				["TransDefBase"] = 150,
				["TransMaxHpBase"] = 1500,
				["TransRunSpeed"] = 160,
				["TransSpeedBase"] = 30,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16016,
				["SkillName"] = "幻化技·魔能机甲",
				["SkillType"] = 2,
				["TransAtkBase"] = 150,
				["TransDefBase"] = 150,
				["TransMaxHpBase"] = 1500,
				["TransRunSpeed"] = 160,
				["TransSpeedBase"] = 30,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16009,
				["SkillName"] = "幻化技·神圣格里芬",
				["SkillType"] = 2,
				["TransAtkBase"] = 175,
				["TransDefBase"] = 175,
				["TransMaxHpBase"] = 1750,
				["TransRunSpeed"] = 150,
				["TransSpeedBase"] = 35,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16013,
				["SkillName"] = "幻化技·碧蓝羽蛇神",
				["SkillType"] = 2,
				["TransAtkBase"] = 175,
				["TransDefBase"] = 175,
				["TransMaxHpBase"] = 1750,
				["TransRunSpeed"] = 150,
				["TransSpeedBase"] = 35,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16008,
				["SkillName"] = "幻化技·暴君雷克斯",
				["SkillType"] = 2,
				["TransAtkBase"] = 200,
				["TransDefBase"] = 200,
				["TransMaxHpBase"] = 2000,
				["TransRunSpeed"] = 180,
				["TransSpeedBase"] = 40,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16012,
				["SkillName"] = "幻化技·彩",
				["SkillType"] = 2,
				["TransAtkBase"] = 225,
				["TransDefBase"] = 225,
				["TransMaxHpBase"] = 2250,
				["TransRunSpeed"] = 170,
				["TransSpeedBase"] = 45,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16010,
				["SkillName"] = "幻化技·光",
				["SkillType"] = 2,
				["TransAtkBase"] = 250,
				["TransDefBase"] = 250,
				["TransMaxHpBase"] = 2500,
				["TransRunSpeed"] = 180,
				["TransSpeedBase"] = 50,
			},
			{
				["SkillDesc"] = "坐骑等级越高，属性加成越高",
				["SkillIcon"] = 16018,
				["SkillName"] = "幻化技·紫晶神兽",
				["SkillType"] = 2,
				["TransAtkBase"] = 125,
				["TransDefBase"] = 125,
				["TransMaxHpBase"] = 1250,
				["TransRunSpeed"] = 150,
				["TransSpeedBase"] = 25,
			},
			[0] = {
				["SkillIcon"] = 1,
				["SkillName"] = "无",
				["SkillType"] = 2,
				["TransAtkBase"] = 0,
				["TransDefBase"] = 0,
				["TransMaxHpBase"] = 0,
				["TransRunSpeed"] = 0,
				["TransSpeedBase"] = 0,
			},
		},
	},
	["Name2Atr"] = {
		[" 战斗力"] = "Fighting",
		["品质"] = "Quality",
		["坐骑ID"] = "Id",
		["坐骑名称"] = "Name",
		["基础攻击"] = "AtkBase",
		["基础生命"] = "MaxHpBase",
		["基础移动速度"] = "BaseRunSpeed",
		["基础速度"] = "SpeedBase",
		["基础防御"] = "DefBase",
		["天赋技"] = "TalentSkillList",
		["头像"] = "FaceIcon",
		["守护技能ID"] = "GuardSkill",
		["幻化ID"] = "TransId",
		["幻化基础攻击"] = "TransAtkBase",
		["幻化基础生命"] = "TransMaxHpBase",
		["幻化基础速度"] = "TransSpeedBase",
		["幻化基础防御"] = "TransDefBase",
		["幻化技能ID"] = "TransSkillId",
		["幻化攻击"] = "TransAtk",
		["幻化生命"] = "TransMaxHp",
		["幻化移动速度"] = "TransRunSpeed",
		["幻化速度"] = "TransSpeed",
		["幻化防御"] = "TransDef",
		["成功率"] = "SuccessRate",
		["技能名称"] = "SkillName",
		["技能图标资源ID"] = "SkillIcon",
		["技能描述文字"] = "SkillDesc",
		["技能类型"] = "SkillType",
		["攻击"] = "Atk",
		["星级"] = "Level",
		["是否飞行"] = "IsFly",
		["生命"] = "MaxHp",
		["祝福值"] = "BlessValue",
		["祝福值上限"] = "BlessLimit",
		["移动速度"] = "RunSpeed",
		["等级上限"] = "LevelLimit",
		["等阶"] = "EvoLevel",
		["经验值"] = "Exp",
		["经验值上限"] = "MaxExp",
		["进阶消耗道具ID"] = "NeedItems",
		["进阶消耗道具数量"] = "NeedItemAmount",
		["进阶消耗金币量"] = "NeedMoney",
		["进阶目标坐骑ID"] = "TargetId",
		["速度"] = "Speed",
		["造型"] = "ShapeId",
		["防御"] = "Def",
	},
	["Name2Id"] = {
		["傲世霸王"] = 80,
		["光辉"] = 100,
		["冰狼"] = 20,
		["圣徒"] = 90,
		["地狱爵士"] = 60,
		["战熊"] = 40,
		["星骓"] = 50,
		["独角兽王"] = 70,
		["白虎"] = 30,
		["飞鸿"] = 10,
	},
	["RelationAttr"] = {
		["BlessValue"] = {
			["SuccessRate"] = true,
		},
		["Id"] = {
			["Atk"] = true,
			["AtkBase"] = true,
			["BaseRunSpeed"] = true,
			["BlessLimit"] = true,
			["Def"] = true,
			["DefBase"] = true,
			["EvoLevel"] = true,
			["FaceIcon"] = true,
			["Fighting"] = true,
			["GuardSkill"] = true,
			["IsFly"] = true,
			["Level"] = true,
			["LevelLimit"] = true,
			["MaxExp"] = true,
			["MaxHp"] = true,
			["MaxHpBase"] = true,
			["NeedItemAmount"] = true,
			["NeedItems"] = true,
			["NeedMoney"] = true,
			["Quality"] = true,
			["RunSpeed"] = true,
			["ShapeId"] = true,
			["Speed"] = true,
			["SpeedBase"] = true,
			["SuccessRate"] = true,
			["TalentSkillList"] = true,
			["TargetId"] = true,
		},
		["TransAtk"] = {
			["Atk"] = true,
			["Fighting"] = true,
		},
		["TransDef"] = {
			["Def"] = true,
			["Fighting"] = true,
		},
		["TransMaxHp"] = {
			["Fighting"] = true,
			["MaxHp"] = true,
		},
		["TransSkillId"] = {
			["RunSpeed"] = true,
			["SkillDesc"] = true,
			["SkillIcon"] = true,
			["SkillName"] = true,
			["SkillType"] = true,
			["TransAtkBase"] = true,
			["TransDefBase"] = true,
			["TransMaxHpBase"] = true,
			["TransRunSpeed"] = true,
			["TransSpeedBase"] = true,
		},
		["TransSpeed"] = {
			["Fighting"] = true,
			["Speed"] = true,
		},
	},
	["TransSkillName2Id"] = {
		["幻化技·光"] = 18,
		["幻化技·彤云天马"] = 11,
		["幻化技·彩"] = 17,
		["幻化技·战马"] = 2,
		["幻化技·暴君雷克斯"] = 16,
		["幻化技·核弹头"] = 8,
		["幻化技·梦魇战骑"] = 5,
		["幻化技·水晶圣兽"] = 9,
		["幻化技·熊猫銮"] = 7,
		["幻化技·玩具火箭"] = 6,
		["幻化技·皇族狮鹫"] = 10,
		["幻化技·碧蓝羽蛇神"] = 15,
		["幻化技·神圣格里芬"] = 14,
		["幻化技·秘银战车"] = 12,
		["幻化技·紫晶神兽"] = 19,
		["幻化技·装甲熊"] = 4,
		["幻化技·雪原狼"] = 3,
		["幻化技·飞鸿"] = 1,
		["幻化技·魔能机甲"] = 13,
		["无"] = 0,
	},
}